# Optimization is turned off by default. Dex does not like code run
# through the ProGuard optimize and preverify steps (and performs some
# of these optimizations on its own).
-dontoptimize
-dontpreverify
-dontobfuscate

-dontskipnonpubliclibraryclasses
-dontskipnonpubliclibraryclassmembers

-keepattributes *Annotation*
-keepattributes Signature

# Tests are called using a reflection mechanism
# Keep all classes related to the test and all classes extending them.
-keep class com.intel.**
-keepclassmembers class com.intel.** {*;}
-keep class ** extends com.intel.mttest.**
-keepclassmembers class ** extends com.intel.mttest.** {*;}

# Vecmath has GPL2 license so we don't shrink it
-keep class javax.vecmath.**
-keepclassmembers class javax.vecmath.** {*;}

# Boofcv uses reflection to get this method. We need to keep it.
-keepclassmembers class boofcv.alg.filter.derivative.***{
    public static void process(...);
}

# PdfBox uses reflection to get a SecurityHandler instance
-keep class ** extends org.apache.pdfbox.pdmodel.encryption.SecurityHandler
-keepclassmembers class ** extends org.apache.pdfbox.pdmodel.encryption.SecurityHandler{
    <init>();
    <init>(...);
}

# Keep logging classes (only for Host mode, Device mode works fine even without it)
-keep class ** extends org.apache.commons.logging.Log
-keepclassmembers class ** extends org.apache.commons.logging.Log {*;}
-keep class org.apache.commons.logging.impl.LogFactoryImpl
-keepclassmembers class org.apache.commons.logging.impl.LogFactoryImpl{*;}

# Suppress warnings.
# Proguard cannot find references for some classes we don't use so we add them as exceptions here
-dontwarn **.log4j.**
-dontwarn boofcv.alg.**
-dontwarn boofcv.io.UtilIO
-dontwarn com.badlogic.gdx.utils.GdxBuild
-dontwarn org.apache.commons.logging.impl.**
-dontwarn org.apache.pdfbox.pdmodel.encryption.PublicKeySecurityHandler
-dontwarn org.apache.fontbox.**
-dontwarn org.ddogleg.optimization.impl.LevenbergBase


# Android stuff.
-keep public class ** extends android.app.Activity
-keep public class ** extends android.app.Application
-keep public class ** extends android.app.Service
-keep public class ** extends android.content.BroadcastReceiver
-keep public class ** extends android.content.ContentProvider

# For native methods, see http://proguard.sourceforge.net/manual/examples.html#native
-keepclasseswithmembernames class ** {
    native <methods>;
}

# keep setters in Views so that animations can still work.
# see http://proguard.sourceforge.net/manual/examples.html#beans
-keep public class ** extends android.view.View {
    public <init>(android.content.Context);
    public <init>(android.content.Context, android.util.AttributeSet);
    public <init>(android.content.Context, android.util.AttributeSet, int);
    public void set*(...);
    *** get*();
}

# We want to keep methods in Activity that could be used in the XML attribute onClick
-keepclassmembers class ** extends android.app.Activity {
   public void *(android.view.View);
}

# For enumeration classes, see http://proguard.sourceforge.net/manual/examples.html#enumerations
-keepclassmembers enum ** {
    public static **[] values();
    public static ** valueOf(java.lang.String);
}

-keepclassmembers class ** implements android.os.Parcelable {
  public static final android.os.Parcelable$Creator CREATOR;
}

-keepclassmembers class **.R$* {
    public static <fields>;
}

# The support library contains references to newer platform versions.
# Don't warn about those in case this app is linking against an older
# platform version.  We know about them, and they are safe.
-dontwarn android.support.**

